WITH 
USUARIOS_SD AS (
     SELECT  *  FROM       
        (SELECT A.* ,
        ROW_NUMBER() OVER(PARTITION BY A.SUBSCRIBER_ID ORDER BY FECHA_REFERENCIA DESC,CANAL ASC) ORDEN
        FROM WOM_AA_GEOREF_TOTAL A)
     Where ORDEN = 1
  --  WHERE MOVIMIENTO_TIPO_NOMBRE IN ('CHURN VOLUNTARIO','CHURN PORTACION')
    --WHERE SUBSCRIBER_ID = 1113139538 
    )  ,

USUARIOS AS (
SELECT * FROM USUARIOS_SD
WHERE 
(CANAL = 'CHURN' AND FECHA_REFERENCIA BETWEEN '28/03/23' AND '04/04/23')
OR
(CANAL = 'PUC' AND FECHA_REFERENCIA BETWEEN '28/03/23' AND '04/04/23'
OR
(CANAL = 'ENCUESTAS' AND FECHA_REFERENCIA BETWEEN '28/03/23' AND '04/04/23')
)

, TRAF_USURIOS AS (
    SELECT 
        U.SUBSCRIBER_ID, 
        U.MSISDN, 
        U.FECHA_ALTA, 
        U.FECHA_BAJA,
        U.CANAL,
        U.FECHA_REFERENCIA,
        U.ESTADO,
        U.MOVIMIENTO_TIPO_NOMBRE,
        A.PERIODO_PROCESO_CODIGO, 
        A.PLMNID, 
        A.OPERADOR, 
        A.ID_CELDA, 
        A.RAT, 
        A.LAC_TAC, 
        A.CELL_ID, 
        A.NUM_CELULAR, 
        A.MNC, 
        A.BYTES, 
        A.CANT_CDRS
    FROM USUARIOS U
    LEFT JOIN CDR_BODEGA_WOM.AGR_TRAFICO_DROU_GEOESPACIAL A ON U.MSISDN = A.NUM_CELULAR
    WHERE A.PERIODO_PROCESO_CODIGO BETWEEN TO_NUMBER(TO_CHAR(U.FECHA_REFERENCIA - 30,'YYYYMMDD')) AND TO_NUMBER(TO_CHAR(U.FECHA_REFERENCIA,'YYYYMMDD'))
    )
,TRAF_COORDENADAS_PROPIA AS (
    SELECT  
    A.SUBSCRIBER_ID, 
    A.MSISDN, 
    A.FECHA_ALTA, 
    A.FECHA_BAJA, 
    A.FECHA_REFERENCIA,
    A.ESTADO,
    A.MOVIMIENTO_TIPO_NOMBRE,
    A.CANAL,
    A.PERIODO_PROCESO_CODIGO,
    A.PLMNID, 
    CASE WHEN UPPER(A.OPERADOR) IN ('AVANTEL','WOM') THEN 'RED_PROPIA' ELSE 'RED_NO_PROPIA' END AS RED,  
    A.ID_CELDA, 
    A.RAT, 
    A.LAC_TAC, 
    A.CELL_ID, 
    A.NUM_CELULAR, 
    A.MNC, 
    A.BYTES, 
    A.CANT_CDRS,
    B.LATITUD, 
    B.LONGITUD, 
    B.NODO, 
    B.RAT_TYPE, 
    UPPER(B.DEPARTAMENTO_CEL) DEPARTAMENTO, 
    UPPER(B.MUNICIPIO_CEL) MUNICIPIO, 
    UPPER(B.LOCALIDAD_CEL) LOCALIDAD, 
    UPPER(B.BARRIO_CEL) BARRIO
    FROM TRAF_USURIOS A
    LEFT JOIN COORDENADAS B ON (A.CELL_ID = B.CELL_ID AND A.MNC=B.MNC)
    WHERE A.MNC IN ('130','360')
    )

--ANTENAS DE INTERES--
,TRAF_COORDENADAS_NOPROPIA AS ( 
SELECT
    A.SUBSCRIBER_ID, 
    A.MSISDN, 
    A.FECHA_ALTA, 
    A.FECHA_BAJA, 
    A.FECHA_REFERENCIA,
    A.ESTADO,
    A.MOVIMIENTO_TIPO_NOMBRE,
    A.CANAL,
    A.PERIODO_PROCESO_CODIGO,
    A.PLMNID, 
    CASE WHEN UPPER(A.OPERADOR) IN ('AVANTEL','WOM') THEN 'RED_PROPIA' ELSE 'RED_NO_PROPIA' END AS RED,  
    A.ID_CELDA, 
    A.RAT, 
    A.LAC_TAC, 
    A.CELL_ID, 
    A.NUM_CELULAR, 
    A.MNC, 
    A.BYTES, 
    A.CANT_CDRS,
    B.LATITUD, 
    B.LONGITUD, 
    B.NODO, 
    B.RAT_TYPE, 
    UPPER(B.DEPARTAMENTO_CEL) DEPARTAMENTO, 
    UPPER(B.MUNICIPIO_CEL) MUNICIPIO, 
    UPPER(B.LOCALIDAD_CEL) LOCALIDAD, 
    UPPER(B.BARRIO_CEL) BARRIO
    FROM TRAF_USURIOS A
    LEFT JOIN COORDENADAS B ON 
    (
    A.CELL_ID = B.CELL_ID 
    AND A.LAC_TAC = B.LAC_TAC
    AND A.MNC = B.MNC
    )
    WHERE A.MNC IN ('101','103','123')
 )

,TRAF_COORDENADAS AS (
        SELECT /*+PARALLEL(8)*/ * FROM TRAF_COORDENADAS_PROPIA
        UNION ALL
        SELECT /*+PARALLEL(8)*/ * FROM TRAF_COORDENADAS_NOPROPIA
        )
           
        ,
        
--RIP AREA--
AGRUP1 AS (        
    SELECT /*+PARALLEL(8)*/ 
        SUBSCRIBER_ID, 
        MSISDN, 
       FECHA_ALTA,
       FECHA_BAJA,
       FECHA_REFERENCIA,
        RED,  
        CANAL,
        LAC_TAC, 
        CELL_ID, 
        MNC, 
        LATITUD, 
        LONGITUD,
        DEPARTAMENTO, 
        MUNICIPIO, 
        LOCALIDAD, 
        BARRIO,
        SUM(BYTES) BYTES,
        SUM(CANT_CDRS) CANT_CDRS
    FROM TRAF_COORDENADAS
    GROUP BY 
        SUBSCRIBER_ID, 
        MSISDN, 
       FECHA_ALTA,
       FECHA_BAJA,
       FECHA_REFERENCIA,
       CANAL,
        RED,  
       CANAL,
        LAC_TAC, 
        CELL_ID, 
        MNC, 
        LATITUD, 
        LONGITUD,
        DEPARTAMENTO, 
        MUNICIPIO, 
        LOCALIDAD, 
        BARRIO
        )
--ROW_NUMBER        
,ANTENA AS (     
    SELECT /*+PARALLEL(8)*/ * 
        FROM (
             SELECT /*+PARALLEL(8)*/
                    A.*
                    ,ROW_NUMBER() OVER(PARTITION BY SUBSCRIBER_ID,RED,CANAL,MSISDN,FECHA_REFERENCIA  ORDER BY  A.FECHA_REFERENCIA DESC, A.SUBSCRIBER_ID DESC, A.CANAL DESC,A.FECHA_REFERENCIA DESC, A.RED DESC, A.BYTES DESC) ORDEN
    FROM AGRUP1 A
    WHERE A.DEPARTAMENTO IS NOT NULL )
    WHERE ORDEN = 1
    )

,   
CDRS_TT AS (       
    SELECT /*+PARALLEL(8)*/
        SUBSCRIBER_ID, 
        MSISDN,
        RED, 
        CANAL,
        FECHA_REFERENCIA,
        SUM(BYTES) AS BYTES_TT, 
        SUM(CANT_CDRS) AS CANT_CDRS_TT
    FROM AGRUP1
        GROUP BY 
            SUBSCRIBER_ID, 
            MSISDN,
            RED,
            CANAL,
            FECHA_REFERENCIA
            )          ,

MPIO AS (       
    SELECT /*+PARALLEL(8)*/
        FECHA_REFERENCIA, 
        SUBSCRIBER_ID, 
        MSISDN, 
        RED, 
        CANAL,
        MUNICIPIO,
        SUM(BYTES) AS BYTES_MPIO, 
        SUM(CANT_CDRS) AS CANT_CDRS_MPIO
    FROM AGRUP1
        GROUP BY 
            FECHA_REFERENCIA, 
            SUBSCRIBER_ID, 
            MSISDN, 
            RED,
            CANAL,
            MUNICIPIO
            ) 
               
            ,
MPIO1 AS ( 
    SELECT /*+PARALLEL(8)*/
        A.FECHA_REFERENCIA,
        A.SUBSCRIBER_ID, 
        A.MSISDN, 
        A.RED, 
        A.CANAL,
        A.MUNICIPIO,
        A.BYTES_MPIO, 
        A.CANT_CDRS_MPIO
    FROM (
        SELECT /*+PARALLEL(8)*/
            FECHA_REFERENCIA, 
            SUBSCRIBER_ID, 
            MSISDN, 
            RED, 
            CANAL,
            MUNICIPIO,
            BYTES_MPIO, 
            CANT_CDRS_MPIO,
            ROW_NUMBER() OVER(PARTITION BY SUBSCRIBER_ID,  RED  ORDER BY   SUBSCRIBER_ID DESC, RED DESC, BYTES_MPIO DESC) ORDEN
        FROM MPIO 
        WHERE MUNICIPIO IS NOT NULL) A
    WHERE ORDEN = 1
   
  )
  ,
 
BD_FIN AS (   
    SELECT  /*+PARALLEL(8)*/ 
        U.SUBSCRIBER_ID, 
        U.MSISDN, 
        U.FECHA_ALTA, 
        U.FECHA_BAJA, 
        U.FECHA_REFERENCIA,
--        U.SERVICIO, 
        U.MOVIMIENTO_TIPO_NOMBRE, 
--        U.CONSULTOR_CANAL_NOMBRE,
        U.CANAL,
        A.RED, 
        A.LAC_TAC, 
        A.CELL_ID, 
        A.MNC, 
        A.LATITUD, 
        A.LONGITUD,
        A.DEPARTAMENTO, 
        A.MUNICIPIO, 
        A.LOCALIDAD, 
        A.BARRIO,
        A.BYTES AS BYTES_ANTE, 
        A.CANT_CDRS AS CANT_CDRS_ANTE, 
        M.BYTES_MPIO,
        M.CANT_CDRS_MPIO,
        T.BYTES_TT,
        T.CANT_CDRS_TT,
        ROUND((A.BYTES/T.BYTES_TT),2) AS PORC_ANTENA_BT,
        ROUND((M.BYTES_MPIO/T.BYTES_TT),2) AS PORC_MPIO_BT,
        ROUND((A.CANT_CDRS/T.CANT_CDRS_TT),2) AS PORC_ANTENA_CDRs,
        ROUND((M.CANT_CDRS_MPIO/T.CANT_CDRS_TT),2) AS PORC_MPIO_CDRs
    FROM USUARIOS U
    LEFT JOIN ANTENA A ON (U.FECHA_REFERENCIA = A.FECHA_REFERENCIA AND U.SUBSCRIBER_ID=A.SUBSCRIBER_ID AND U.MSISDN=A.MSISDN)
    LEFT JOIN MPIO1 M ON (A.FECHA_REFERENCIA = M.FECHA_REFERENCIA AND A.SUBSCRIBER_ID=M.SUBSCRIBER_ID AND A.MSISDN=M.MSISDN AND A.RED=M.RED AND A.CANAL=M.CANAL )
    LEFT JOIN CDRS_TT T ON (A.FECHA_REFERENCIA = T.FECHA_REFERENCIA AND A.SUBSCRIBER_ID=T.SUBSCRIBER_ID AND A.MSISDN=T.MSISDN AND A.RED=T.RED AND A.CANAL=T.CANAL)
    )
    
SELECT /*+PARALLEL(8)*/  * FROM BD_FIN;