WITH NEVER_PB AS (SELECT
subs_id_gross subs,
periodo_gross as ppc,
RANK() OVER (PARTITION BY subs_id_gross ORDER BY periodo_gross DESC) as orden,
concepto
From CARTERA_WOM.XLS_NUNCA_PAGO_Y_FACTURADO NEVER
)
,NEVER as (
select 
*
from NEVER_PB
where orden =1
)

,ENDING AS (
SELECT
END.*,
CONCEPTO,
PPC,
TO_CHAR(TO_DATE(fecha_alta, 'DD/MM/YY'), 'YYYYMM') AS PPC_ALTA
FROM  BI_WOM.AGG_DL_SUBS_ENDING_MOVIM END
LEFT JOIN NEVER ON
END.SUBSCRIBER_ID = NEVER.SUBS 
AND END.ESTADO = 'Termination'
--AND END.MOVIMIENTO_TIPO_NOMBRE = 'DESCONEXION'
WHERE PERIODO_PROCESO_CODIGO = 202301
AND SERVICIO = 'Postpaid'
and subscriber_id NOT IN (SELECT subscriber_id FROM WOM_AA_USUARIOS_FRAUDE))


,ANTIGUEDAD as (select 
ENDING.*,
MONTHS_BETWEEN(TO_DATE(periodo_proceso_codigo, 'YYYYMM'), TO_DATE(PPC_ALTA, 'YYYYMM')) as ANTIGUEDAD
from ENDING)

,SENIORITY as (select ANTIGUEDAD.*,
case when ANTIGUEDAD in (0,1,2,3) then 'EARLY' 
when ANTIGUEDAD in(4,5,6) then 'MIDDLE'
when ANTIGUEDAD >6 then 'STRUCTURAL' end as Seniority
from ANTIGUEDAD) 

,NUEVO_ESTADO AS(SELECT
SUBSCRIBER_ID, 
MOVIMIENTO_NOMBRE,
--CASE WHEN MOVIMIENTO_NOMBRE LIKE '%ACTIVACION%' THEN 'ACTIVACION'
--     WHEN MOVIMIENTO_NOMBRE LIKE '%PERMANECE%' THEN 'PERMANECE'
--     WHEN MOVIMIENTO_NOMBRE LIKE '%DESCONEXION%' THEN 'DESCONEXION' END AS MOVIMIENTO_NOMBRE ,
CASE WHEN CONCEPTO IS NOT NULL THEN UPPER(CONCEPTO) 
     WHEN CONCEPTO IS NULL THEN SENIORITY END AS SENIORITY,
ESTADO,
MOVIMIENTO_TIPO_NOMBRE
FROM SENIORITY)

select count(DISTINCT subscriber_id), seniority
from NUEVO_ESTADO
where MOVIMIENTO_NOMBRE = 'OPENING'
--AND ESTADO ='Termination'
group by seniority

