DROP TABLE wom_aa_top3_celdas_lite_filas ;
COMMIT;

CREATE TABLE wom_aa_top3_celdas_lite_filas AS

WITH 
USUARIOS AS (
     SELECT  *  FROM       
        (SELECT A.* ,
        ROW_NUMBER() OVER(PARTITION BY A.SUBSCRIBER_ID ORDER BY PERIODO_PROCESO_CODIGO,FECHA_ALTA) ORDEN
        FROM DWH_BODEGA_WOM.FCT_SUBSCRIBERS_ENDING A
        WHERE PERIODO_PROCESO_CODIGO = 202306
--        and SUBSCRIBER_ID = 1254140474
        )
     Where ORDEN = 1
  --  WHERE MOVIMIENTO_TIPO_NOMBRE IN ('CHURN VOLUNTARIO','CHURN PORTACION')
    --WHERE SUBSCRIBER_ID = 1113139538 
    )  

, TRAF_USURIOS AS (
    SELECT /*+PARALLEL(8)*/
        U.SUBSCRIBER_ID, 
        U.MSISDN, 
        U.FECHA_ALTA, 
        U.FECHA_BAJA,
        U.SERVICIO,
        A.SEMANA,
--        U.CANAL,
--        U.FECHA_REFERENCIA,
        U.ESTADO,
        U.MOVIMIENTO_TIPO_NOMBRE,
        A.PERIODO_PROCESO_CODIGO, 
        A.PLMNID, 
        A.OPERADOR, 
        A.ID_CELDA, 
        A.RAT, 
        A.LAC_TAC, 
        A.CELL_ID, 
        A.NUM_CELULAR, 
        A.MNC, 
        A.BYTES, 
        A.CANT_CDRS
    FROM USUARIOS U
    LEFT JOIN CDR_BODEGA_WOM.AGR_TRAFICO_DROU_GEOESPACIAL A ON U.MSISDN = A.NUM_CELULAR
    WHERE A.PERIODO_PROCESO_CODIGO BETWEEN 20230520 AND 20230620
    )
     
,TRAF_COORDENADAS_PROPIA AS (
    SELECT  
    A.SUBSCRIBER_ID, 
    A.MSISDN, 
    A.FECHA_ALTA, 
    A.FECHA_BAJA, 
    A.SERVICIO,
    A.SEMANA,
--    A.FECHA_REFERENCIA,
    A.ESTADO,
    A.MOVIMIENTO_TIPO_NOMBRE,
--    A.CANAL,
    A.PERIODO_PROCESO_CODIGO,
    A.PLMNID, 
    CASE WHEN UPPER(A.OPERADOR) IN ('AVANTEL','WOM') THEN 'RED_PROPIA' ELSE 'RED_NO_PROPIA' END AS RED,  
    A.ID_CELDA, 
    A.RAT, 
    A.LAC_TAC, 
    A.CELL_ID, 
    A.NUM_CELULAR, 
    A.MNC, 
    A.BYTES, 
    A.CANT_CDRS,
    B.LATITUD, 
    B.LONGITUD, 
    B.NODO, 
    B.RAT_TYPE, 
    UPPER(B.DEPARTAMENTO_CEL) DEPARTAMENTO, 
    UPPER(B.MUNICIPIO_CEL) MUNICIPIO, 
    UPPER(B.LOCALIDAD_CEL) LOCALIDAD, 
    UPPER(B.BARRIO_CEL) BARRIO
    FROM TRAF_USURIOS A
    LEFT JOIN COORDENADAS B ON (A.CELL_ID = B.CELL_ID AND A.MNC=B.MNC)
    WHERE A.MNC IN ('130','360')
    )

--ANTENAS DE INTERES--
,TRAF_COORDENADAS_NOPROPIA AS ( 
SELECT
    A.SUBSCRIBER_ID, 
    A.MSISDN, 
    A.FECHA_ALTA, 
    A.FECHA_BAJA, 
    A.SERVICIO,
    A.SEMANA,
--    A.FECHA_REFERENCIA,
    A.ESTADO,
    A.MOVIMIENTO_TIPO_NOMBRE,
--    A.CANAL,
    A.PERIODO_PROCESO_CODIGO,
    A.PLMNID, 
    CASE WHEN UPPER(A.OPERADOR) IN ('AVANTEL','WOM') THEN 'RED_PROPIA' ELSE 'RED_NO_PROPIA' END AS RED,  
    A.ID_CELDA, 
    A.RAT, 
    A.LAC_TAC, 
    A.CELL_ID, 
    A.NUM_CELULAR, 
    A.MNC, 
    A.BYTES, 
    A.CANT_CDRS,
    B.LATITUD, 
    B.LONGITUD, 
    B.NODO, 
    B.RAT_TYPE, 
    UPPER(B.DEPARTAMENTO_CEL) DEPARTAMENTO, 
    UPPER(B.MUNICIPIO_CEL) MUNICIPIO, 
    UPPER(B.LOCALIDAD_CEL) LOCALIDAD, 
    UPPER(B.BARRIO_CEL) BARRIO
    FROM TRAF_USURIOS A
    LEFT JOIN COORDENADAS B ON 
    (
    A.CELL_ID = B.CELL_ID 
    AND A.LAC_TAC = B.LAC_TAC
    AND A.MNC = B.MNC
    )
    WHERE A.MNC IN ('101','103','123')
 )

,TRAF_COORDENADAS AS (
        SELECT /*+PARALLEL(8)*/ * FROM TRAF_COORDENADAS_PROPIA
        UNION ALL
        SELECT /*+PARALLEL(8)*/ * FROM TRAF_COORDENADAS_NOPROPIA
        )      
        ,
        
--RIP AREA--
AGRUP1 AS (        
    SELECT /*+PARALLEL(8)*/ 
        SUBSCRIBER_ID, 
        MSISDN, 
       FECHA_ALTA,
       FECHA_BAJA,
       SEMANA,
       SERVICIO,
--       FECHA_REFERENCIA,
        RED,  
--        CANAL,
        LAC_TAC, 
        CELL_ID, 
        MNC, 
        LATITUD, 
        LONGITUD,
        DEPARTAMENTO, 
        MUNICIPIO, 
        LOCALIDAD, 
        BARRIO,
        SUM(BYTES) BYTES,
        SUM(CANT_CDRS) CANT_CDRS
    FROM TRAF_COORDENADAS
    GROUP BY 
        SUBSCRIBER_ID, 
        MSISDN, 
       FECHA_ALTA,
       FECHA_BAJA,
       SERVICIO,
       SEMANA,
--       FECHA_REFERENCIA,
       RED,  
--       CANAL,
        LAC_TAC, 
        CELL_ID, 
        MNC, 
        LATITUD, 
        LONGITUD,
        DEPARTAMENTO, 
        MUNICIPIO, 
        LOCALIDAD, 
        BARRIO
        )

,ANTENA AS (     
    SELECT /*+PARALLEL(8)*/  * 
        FROM (
             SELECT 
                    A.*
                    ,ROW_NUMBER() OVER(PARTITION BY SUBSCRIBER_ID,MSISDN,SEMANA  ORDER BY  SEMANA DESC, SUBSCRIBER_ID DESC, A.RED DESC, A.BYTES DESC) TOP_CELDA 
--                    ,RATIO_TO_REPORT(BYTES) OVER (PARTITION BY SUBSCRIBER_ID, SEMANA ORDER BY bytes DESC) AS USO_ANTENA
                    ,ROUND ((RATIO_TO_REPORT(BYTES) OVER (PARTITION BY SUBSCRIBER_ID,SEMANA)),2) AS PORC_USO_CELDA
    FROM AGRUP1 A
--    WHERE A.DEPARTAMENTO IS NOT NULL
)
    WHERE TOP_CELDA <=3
    )


SELECT   /*+PARALLEL(8)*/  
    SUBSCRIBER_ID ,
    MSISDN,
    SEMANA,
    SERVICIO,
    CELL_ID,
    LAC_TAC,
    MNC,
    TOP_CELDA,
    PORC_USO_CELDA,
    BYTES,
    CASE 
        WHEN SUM(ANTENA.PORC_USO_CELDA) OVER (PARTITION BY ANTENA.SUBSCRIBER_ID, ANTENA.SEMANA) >= 0.5 THEN 'ESTATICO'
        ELSE 'MOVIL'
    END AS TIPO_USUARIO,
    LATITUD, 
    LONGITUD
FROM ANTENA
ORDER BY
SUBSCRIBER_ID,
SEMANA,
TOP_CELDA

;
COMMIT;



