select /*+PARALLEL(8)*/
A.* ,
B.SUBSCRIBER_ID,
C.IMEI,
D.*
from wom_aa_georef_puc A 
LEFT JOIN DWH_BODEGA_WOM.FCT_SUBSCRIBERS_ENDING B ON A.MSISDN = B.MSISDN AND B.PERIODO_PROCESO_CODIGO = 202305
LEFT JOIN DWH_STAGE_WOM.STG_TRIPLETA C ON A.MSISDN = C.MSISDN
INNER JOIN wom_aa_top3_celdas_lite_filas D ON B.SUBSCRIBER_ID = D.SUBSCRIBER_ID