DROP TABLE WOM_AA_GEOREF_QUALTRICS ;

CREATE TABLE WOM_AA_GEOREF_QUALTRICS AS

with detractores as 
(SELECT a.*,
TO_CHAR(TO_DATE(FECHA_REFERENCIA, 'MM/DD/YY HH24:MI'), 'IW') as SEMANA_REFERENCIA,
'DETRACTOR' as CATEGORIA
FROM wom_aa_georef_encuestas a
WHERE TO_DATE(fecha_referencia, 'MM/DD/RR HH24:MI') > TO_DATE('06/13/23 00:00', 'MM/DD/RR HH24:MI')
and ( 
DET_RECOM = 'Detractor'
or DET_VOZ = 'Si'
or DET_DATOS = 'Si')
)

select 

A.FECHA_REFERENCIA,
A.SEMANA_REFERENCIA,
A.DET_RECOM,
A.MOTIVO_RECOM,
A.DET_DATOS,
A.MOTIVO_DATOS,
A.DET_VOZ,
A.MOTIVO_VOZ,
A.CATEGORIA,
B.*
FROM DETRACTORES A
inner join wom_aa_top3_celdas_lite_filas b
on a.subscriber_id = b.subscriber_id
where b.SEMANA = a.SEMANA_REFERENCIA 
or b.SEMANA = a.SEMANA_REFERENCIA - 1
;
SELECT * FROM WOM_AA_GEOREF_QUALTRICS