DROP TABLE WOM_AA_GEOREF_DETEL ;
COMMIT;

CREATE TABLE WOM_AA_GEOREF_DETEL AS 

with DET as (
SELECT*FROM 
(SELECT
PERIODO_PROCESO_CODIGO, 
CALL_CENTER, 
NUMERO_ORIGEN, 
FECHALLAMADA, 
SENTIDO, 
LLAMADA, 
TIPIFICACION, 
RECOMENDAR,
'DETRACTOR'
FROM BPO_BODEGA_WOM.CALL_CENTER_WOM
where FECHALLAMADA >= '2023/06/27 00:00:00'
and SENTIDO in ('Entrante') and LLAMADA in ('Atendido')
and RECOMENDAR in ('0','1','2','3','4','5')) A
LEFT JOIN
(SELECT  
A.ORDER_CODE,
SERVICE_TYPE1,
SERVICE_TYPE2,
SERVICE_TYPE3,
SERVICE_TYPE4,
CIUDAD_FALLA,
F.CLIENTE_NOMBRE,
A.CLIENTE_DK CUST_ID,
F.CLIENTE_TIPO_DOCUMENTO,
F.CLIENTE_NIT_CEDULA,
MSISDN SERVICE_NUMBER
FROM
(SELECT * FROM DWH_BODEGA_WOM.FCT_CASOS_ABIERTOS
              WHERE TIEMPO_APERTURA_DK  >= '20230627'
              UNION
              SELECT * FROM DWH_BODEGA_WOM.FCT_CASOS_CERRADOS
              WHERE TIEMPO_APERTURA_DK   >= '20230627' ) A 
LEFT JOIN  DWH_BODEGA_WOM.DIM_CONSULTORES B ON A.CONSULTOR_ACTUAL_DK = B.CONSULTOR_DK
AND TIEMPO_APERTURA_DK BETWEEN TO_CHAR(CONSULTOR_FECHA_INI_VIG,'YYYYMMDD') AND TO_CHAR(CONSULTOR_FECHA_FIN_VIG,'YYYYMMDD')
LEFT JOIN (select SERVICE_TYPE1,SERVICE_TYPE2,SERVICE_TYPE3,SERVICE_TYPE4,SERVICE_TYPE_DK from DWH_BODEGA_WOM.DIM_SERVICE_TYPES) C
ON A.SERVICE_TYPE_DK =  C.SERVICE_TYPE_DK 
LEFT JOIN  DWH_BODEGA_WOM.DIM_CONSULTORES  D ON A.CONSULTOR_APERTURA_DK = D.CONSULTOR_DK
LEFT JOIN  DWH_BODEGA_WOM.DIM_CONSULTORES  E ON A.CONSULTOR_cierre_DK = E.CONSULTOR_DK
LEFT JOIN  DWH_BODEGA_WOM.DIM_CLIENTES F ON A.CLIENTE_DK = F.CLIENTE_DK
WHERE A.ORDER_STATE in ('Cerrar','Enviar')
AND SERVICE_TYPE2 IN ('NOVEDAD EN VOZ','NOVEDAD EN DATOS','NOVEDAD DE SEÑAL')) B
ON A.TIPIFICACION = B.ORDER_CODE
where ORDER_CODE is not null
)

,DETEL AS (
select 
SERVICE_NUMBER AS MSISDN,
FECHALLAMADA AS FECHA_REFERENCIA,
TO_CHAR (TO_DATE(FECHALLAMADA,'YYYY/MM/DD HH24:MI:SS'),'IW') as SEMANA_QUEJA ,
'DETRACTOR TELEFONICO' AS CATEGORIA , 
SERVICE_TYPE1,
SERVICE_TYPE2,
SERVICE_TYPE3
from DET
)

SELECT 
FECHA_REFERENCIA,
SEMANA_QUEJA ,
CATEGORIA , 
SERVICE_TYPE1,
SERVICE_TYPE2,
SERVICE_TYPE3,
B.*
FROM DETEL A
INNER JOIN wom_aa_top3_celdas_lite_filas B
ON A.MSISDN = B.MSISDN 
WHERE B.SEMANA = A.SEMANA_QUEJA
OR B.SEMANA = A.SEMANA_QUEJA -1
;
COMMIT;

SELECT * FROM 
WOM_AA_GEOREF_DETEL
